cryptosyte/cryptosyte/urls.py
#from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from crypto import views

handler404 = 'crypto.views.page_not_found'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('currencies/<slug:currencies_slug>/', views.CurrencyDetailView.as_view(), name='currencies'),
    path('archive/<str:currency_name>/<int:year>/', views.ArchiveView.as_view(), name='archive'),
    path('invalid-year/<str:currency_name>/<int:year>/', views.InvalidYearView.as_view(), name='invalid_year'),
    path('trade/', views.TradeView.as_view(), name='trade'),
    path('markets/', views.PostListView.as_view(), name='markets'),
    path('contact/', views.ContactView.as_view(), name='contact_form'),
    path('delete_comment/<int:pk>/', views.DeleteCommentView.as_view(), name='delete_comment'),
    path('comment/<int:pk>/edit/', views.CommentUpdateView.as_view(), name='edit_comment'),
    path('markets/<int:post_id>/', views.PostListView.as_view(), name='markets'),
    path('users/', include('users.urls', namespace='users'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cryptosyte/users/urls.py
from django.contrib.auth.views import (
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, reverse_lazy
from users import views

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    #path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/<int:pk>/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name='password_change_done'),

    # Маршруты для сброса пароля
    path('password-reset/', PasswordResetView.as_view(
        template_name="users/password_reset_form.html",
        email_template_name="users/password_reset_email.html",
        success_url=reverse_lazy("users:password_reset_done")
    ), name='password_reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name="users/password_reset_done.html"
    ), name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name="users/password_reset_confirm.html",
        success_url=reverse_lazy("users:password_reset_complete")
    ), name='password_reset_confirm'),

    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name="users/password_reset_complete.html"
    ), name='password_reset_complete'),
]

app_name = "users"

cryptosyte/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    bio = models.TextField(blank=True, null=True, verbose_name="Биография")
    location = models.CharField(max_length=255, blank=True, null=True, verbose_name="Местоположение")
    birth_date = models.DateField(null=True, blank=True, verbose_name="Дата рождения")

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"

    def __str__(self):
        return self.user.username

cryptosyte/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from users.models import Profile
User = get_user_model()

# class LoginUserForm(AuthenticationForm):
#     username = forms.CharField(
#         label='Логин',
#         widget=forms.TextInput(attrs={'class': 'form-input'})
#     )
#     password = forms.CharField(
#         label='Пароль',
#         widget=forms.PasswordInput(attrs={'class': 'form-input'})
#     )

class RegisterUserForm(UserCreationForm):
    username = forms.CharField(
        label='Логин',
        widget=forms.TextInput(attrs={'class': 'form-input'})
    )
    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-input'})
    )
    password2 = forms.CharField(
        label='Повтор пароля',
        widget=forms.PasswordInput(attrs={'class': 'form-input'})
    )
    bio = forms.CharField(widget=forms.Textarea, required=False, label="Биография")
    location = forms.CharField(max_length=255, required=False, label="Местоположение")
    birth_date = forms.DateField(
     required=False,
     widget=forms.SelectDateWidget(years=range(1950, 2024)),
     label="Дата рождения"
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email

    def save(self, commit=True):
        user = super().save(commit=False)  # Создаем экземпляр пользователя, но не сохраняем его
        if commit:
            user.save()  # Сохраняем пользователя
            Profile.objects.create(
                user=user,  # Присваиваем экземпляр пользователя, а не класс
                bio=self.cleaned_data['bio'],
                location=self.cleaned_data['location'],
                birth_date=self.cleaned_data['birth_date']
            )
        return user

class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(
        disabled=True,
        label='Логин',
        widget=forms.TextInput(attrs={'class': 'form-input'})
    )
    email = forms.CharField(
        disabled=True,
        label='Email',
        widget=forms.TextInput(attrs={'class': 'form-input'})
    )
    bio = forms.CharField(
        disabled=True,  # Поле только для чтения
        widget=forms.Textarea(attrs={'class': 'form-input'}),
        label='Биография',
        required=False
    )
    location = forms.CharField(
        disabled=True,  # Поле только для чтения
        widget=forms.TextInput(attrs={'class': 'form-input'}),
        label='Местоположение',
        required=False
    )
    birth_date = forms.DateField(
        disabled=True,  # Поле только для чтения
        widget=forms.SelectDateWidget(years=range(1950, 2024)),
        label='Дата рождения',
        required=False
    )

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'bio', 'location', 'birth_date']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Старый пароль",
        widget=forms.PasswordInput(attrs={'class': 'form-input'})
    )
    new_password1 = forms.CharField(
        label="Новый пароль",
        widget=forms.PasswordInput(attrs={'class': 'form-input'})
    )
    new_password2 = forms.CharField(
        label="Подтверждение пароля",
        widget=forms.PasswordInput(attrs={'class': 'form-input'})
    )

cryptosyte/users/views.py
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView
from users.forms import RegisterUserForm, ProfileUserForm, UserPasswordChangeForm
from users.models import Profile
from crypto.models import Comment
from crypto.utils import DataMixin

class LoginUser(LoginView):
 template_name = 'users/login.html'
 extra_context = {'title': "Авторизация"}
 form_class = AuthenticationForm

 def get_success_url(self):
  return self.get_redirect_url() or reverse_lazy('home')


def logout_user(request):
 logout(request)
 return HttpResponseRedirect(reverse('home'))

class RegisterUser(CreateView):
 form_class = RegisterUserForm
 template_name = 'users/register.html'
 extra_context = {'title': "Регистрация"}
 success_url = reverse_lazy('users:login')


class ProfileUser(LoginRequiredMixin, DataMixin, UpdateView):
    model = get_user_model()  # Указывает на модель пользователя
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': "Профиль пользователя"}

    def get_success_url(self):
        return reverse_lazy('users:profile', args=[self.request.user.pk])

    def get_object(self, queryset=None):
        # Получаем профиль пользователя
        return Profile.objects.get(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Добавляем информацию о пользователе
        user = self.request.user
        context['user'] = user

        # Добавляем профиль пользователя
        profile = self.get_object()
        context['profile'] = profile

        # Добавляем комментарии пользователя
        user_comments = Comment.objects.filter(user=user)  # Замените Comment на вашу модель комментариев
        context['user_comments'] = user_comments
        context['comment_count'] = user_comments.count()

        return context

class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"
    extra_context = {'title': "Изменение пароля"}

cryptosyte/users/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
<input type="hidden" name="next" value="{{ next }}" />
<style>
.button-link {
    display: inline-block;
    padding: 4px 6px; /* уменьшение размера кнопок */
    background-color: white;
    color: black;
    border: 1px solid #888888;
    border-radius: 3px;
    text-align: center;
    text-decoration: none;
    font-size: 14px; /* уменьшение размера текста */
    margin-right: 10px; /* небольшое расстояние между кнопками */
}

.button-link:hover {
    background-color: #f0f0f0;
    color: black;
    text-decoration: none;
}

.button-group {
    display: flex;
    justify-content: center;
    margin-top: 20px;
}

button, .button-link {
    font-size: 14px;
    cursor: pointer;
}

</style>
<h1>Авторизация</h1>
<form method="post">
    {% csrf_token %}

    <!-- Вывод общих ошибок формы -->
    <div class="form-error">{{ form.non_field_errors }}</div>

    <!-- Вывод каждого поля формы с его ошибками -->
    {% for f in form %}
        <p>
            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>
            {{ f }}
        </p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <button type="submit">Войти</button>
    <!-- Кнопка отправки формы -->
    <div class="button-group">
    <a href="{% url 'users:register' %}" class="button-link">Зарегистрироваться</a>
    <a href="{% url 'home' %}" class="button-link">Вернуться на главную</a>
    <a href="{% url 'users:password_reset' %}" class="button-link">Забыли пароль?</a>
    </div>
</form>
{% endblock %}

cryptosyte/users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
    <h1>Пароль успешно изменен!</h1>
    <p>
        Вы успешно изменили пароль. 
        <a href="{% url 'users:profile' pk=user.pk %}">Вернуться в профиль.</a>

    </p>
{% endblock %}

cryptosyte/users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>Изменение пароля</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>

        {% for field in form %}
            <p>
                <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}:</label>
                {{ field }}
            </p>
            <div class="form-error">{{ field.errors }}</div>
        {% endfor %}

        <p>
            <button type="submit">Изменить пароль</button>
        </p>
    </form>
{% endblock %}

cryptosyte/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block content %}
    <h1>Пароль изменен</h1>
    <p>
        Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
        <a href="{% url 'users:login' %}">входа в систему</a>.
    </p>
{% endblock %}

cryptosyte/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block content %}

    <h1>Новый пароль</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <p>
                <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
                {{ f }}
            </p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p>
            <button type="submit">Сохранить</button>
        </p>
    </form>
{% endblock %}

cryptosyte/users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <h1>Сброс пароля</h1>
    <p>
        {% translate "Мы отправили вам инструкцию для смены пароля на указанный email, если аккаунт существует." %}
    </p>
    <p>
        {% translate "Вы получите сообщение в ближайшее время. Если вы не получили email, пожалуйста, проверьте введенный адрес и папку со спамом." %}
    </p>
{% endblock %}

cryptosyte/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

cryptosyte/users/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block content %}
    <h1>Восстановление пароля</h1>
    <form method="post">
        {% csrf_token %}
        {% for f in form %}
            <p>
                <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
                {{ f }}
            </p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p>
            <button type="submit">Сбросить по Email</button>
        </p>
    </form>
{% endblock %}

cryptosyte/users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<head>
<style>
    /* Стили для меню */
        .menu-toggle {
            position: fixed;
            left: 0;
            top: 50%;
            transform: translateY(-50%);
            background: #000;
            color: #fff;
            padding: 10px;
            cursor: pointer;
            z-index: 1000; /* Поверх других элементов */
            border-radius: 5px;
            text-align: center;
            transition: opacity 0.3s;
        }

        .nav-menu {
            position: fixed;
            left: -200px; /* Скрыто за пределами экрана */
            top: 50%;
            transform: translateY(-50%);
            background: rgba(0, 0, 0, 0.8); /* Полупрозрачный фон */
            padding: 10px;
            border-radius: 5px;
            transition: left 0.3s; /* Плавное появление */
            z-index: 999; /* Ниже кнопки "меню" */
        }

        .nav-menu a {
            display: block;
            color: #fff;
            padding: 10px;
            text-decoration: none;
            transition: background 0.3s;
        }

        .nav-menu a:hover {
            background: rgba(255, 255, 255, 0.2); /* Цвет при наведении */
        }

        /* Показывать меню при наведении на кнопку и скрывать текст кнопки */
        .menu-toggle:hover {
            opacity: 0; /* Скрываем текст кнопки */
        }

        /* Показать меню при наведении на кнопку */
        .menu-toggle:hover + .nav-menu, .nav-menu:hover {
            left: 0; /* Показать меню */
        }

        .nav-menu:hover + .menu-toggle {
            opacity: 0; /* Скрыть текст кнопки, когда меню активно */
        }
</style>
</head>
<body>
<div class="menu-toggle">Меню</div> <!-- Кнопка для открытия меню -->
    <div class="nav-menu">
        <a href="{{ home_url }}">Домой</a>
        <a href="{{ markets_url }}">Посты</a>
        <a href="{{ trade_url }}">Торговля</a>
        <a href="{{ profile_url }}">Профиль</a>
        <!-- Добавьте другие кнопки по мере необходимости -->
    </div>
    <h1>Профиль</h1>

    <h2>Информация о пользователе</h2>
    <p><strong>Логин:</strong> {{ user.username }}</p>
    <p><strong>Email:</strong> {{ user.email }}</p>
    <p><strong>Имя:</strong> {{ user.first_name }}</p>
    <p><strong>Фамилия:</strong> {{ user.last_name }}</p>
    <p><strong>Дата рождения:</strong> {{ profile.birth_date|date:"d.m.Y" }}</p>
    <p><strong>Биография:</strong> {{ profile.bio|default:"Нет данных" }}</p>
    <p><strong>Локация:</strong> {{ profile.location|default:"Нет данных" }}</p>
    <p ><a href="{% url 'users:password_change' %}">Сменить пароль</a></p>

    <h2>Комментарии пользователя</h2>
    {% if user_comments %}
        <ul>
            {% for comment in user_comments %}
                <li>
                    <strong>{{ comment.created_at }}:</strong>
                    {{ comment.content|default:"Без текста" }}
                    {% if comment.image %}
                        <img src="{{ comment.image.url }}" alt="Изображение" style="max-width: 100px; max-height: 100px;">
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Нет комментариев.</p>
</body>
    {% endif %}
{% endblock %}

cryptosyte/users/templates/users/register.html
{% extends 'base.html' %}
{% block content %}
<style>
.button-link {
    display: inline-block;
    padding: 4px 6px; /* уменьшение размера кнопок */
    background-color: white;
    color: black;
    border: 1px solid #888888;
    border-radius: 3px;
    text-align: center;
    text-decoration: none;
    font-size: 14px; /* уменьшение размера текста */
    margin-right: 10px; /* небольшое расстояние между кнопками */
}

.button-link:hover {
    background-color: #f0f0f0;
    color: black;
    text-decoration: none;
}

.button-group {
    display: flex;
    justify-content: center;
    margin-top: 20px;
}

button, .button-link {
    font-size: 14px;
    cursor: pointer;
}

</style>
<h1>Регистрация</h1>
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />

    <div class="form-error">{{ form.non_field_errors }}</div>

    {% for f in form %}
        <p>
            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
            {{ f }}
        </p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p>
        <button type="submit">Регистрация</button>
    </p>
    <div class="button-group">
    <a href="{% url 'users:login' %}" class="button-link">Войти в существующий аккаунт</a>
    <a href="{% url 'home' %}" class="button-link">Вернуться на главную</a>
    </div>
</form>

{% endblock %}